### ISSUE TITLE
Wrong perl used in tests?

### ISSUE THREAD

**Issue by eserte** [worthmine/App-findeps#1]
On some of my smokers the test suite fails with strange errors like this:
```
Can't load '/home/cpansand/.cpan/build/2020092113/Scalar-List-Utils-1.55-7FRMK0/blib/arch/auto/List/Util/Util.so' for module List::Util: /home/cpansand/.cpan/build/2020092113/Scalar-List-Utils-1.55-7FRMK0/blib/arch/auto/List/Util/Util.so: Undefined symbol "PL_tainting" at /usr/local/lib/perl5/5.24/mach/DynaLoader.pm line 193.
Compilation failed in require at ./script/findeps line 11.
BEGIN failed--compilation aborted at ./script/findeps line 11.

#   Failed test 'succeed to detect 'Dummy''
#   at t/01_pl.t line 11.
#          got: ''
#     expected: 'Dummy'
... (etc) ...
```
This looks like the wrong perl is used for testing --- in this case it's the system's perl, not the perl used for building the distributiion. Using at some point `$^X` could help.

**Comment by worthmine** [comment]
thanks for reviewing!

Do you mean like below?

```pl
my $done = qx"./script/findeps --myLib t/lib $file"; # depends on environment

my $done = qx"$^X ./script/findeps --myLib t/lib $file"; # is more strict
```

except this, I never run Perl with qx or \`\` on tests

btw, [almost of fail](http://matrix.cpantesters.org/?dist=App-findeps%200.03) is `Can't locate FastGlob.pm in @INC~` but it seems to be imported

```
Prerequisite modules loaded:

requires:

    Module              Need     Have    
    ------------------- -------- --------
    FastGlob            1.5      1.5     
    List::Util          1.55     1.55    
    perl                5.012001 5.026002
```

Are both the same problem?

anyway, I have updated the [code](https://github.com/worthmine/App-findeps/commit/6a8ddd6bdcae6faedc98928d2764c22f9e08d71f)

Please try it again with this.

**Comment by worthmine** [comment]
@eserte 
I've never touched any button for closing. It seems that it has been closed by github automatically.

So please close it when you agree with it deserves to close it.

**Comment by worthmine** [comment]
it seems that from 0.04 or higher fixed this Issue. 

http://matrix.cpantesters.org/?dist=App-findeps%200.04
